package cn.syned.crm.settings.entity;

import lombok.Data;

import java.io.Serializable;

/**
 * null
 *
 * @TableName tbl_dic_type
 */
@Data
public class DicType implements Serializable {
    /**
     * 编码是主键，不能为空，不能含有中文。
     *
     * @mbg.generated 2021-02-02 15:08:43
     */
    private String code;

    /**
     * @mbg.generated 2021-02-02 15:08:43
     */
    private String name;

    /**
     * @mbg.generated 2021-02-02 15:08:43
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_dic_type
     *
     * @mbg.generated 2021-02-02 15:08:43
     */
    private static final long serialVersionUID = 1L;
}