package cn.syned.crm.settings.entity;

import lombok.Data;

import java.io.Serializable;

/**
 * null
 *
 * @TableName tbl_dic_value
 */
@Data
public class DicValue implements Serializable {
    /**
     * 主键，采用UUID
     *
     * @mbg.generated 2021-02-02 15:08:43
     */
    private String id;

    /**
     * 不能为空，并且要求同一个字典类型下字典值不能重复，具有唯一性。
     *
     * @mbg.generated 2021-02-02 15:08:43
     */
    private String value;

    /**
     * 可以为空
     *
     * @mbg.generated 2021-02-02 15:08:43
     */
    private String text;

    /**
     * 可以为空，但不为空的时候，要求必须是正整数
     *
     * @mbg.generated 2021-02-02 15:08:43
     */
    private String orderNo;

    /**
     * 外键
     *
     * @mbg.generated 2021-02-02 15:08:43
     */
    private String typeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_dic_value
     *
     * @mbg.generated 2021-02-02 15:08:43
     */
    private static final long serialVersionUID = 1L;
}