package cn.syned.crm.workbench.entity;

import lombok.Data;

import java.io.Serializable;

/**
 * null
 *
 * @TableName tbl_clue
 */
@Data
public class Clue implements Serializable {
    /**
     * @mbg.generated 2021-02-13 17:38:53
     */
    private String id;

    /**
     * @mbg.generated 2021-02-13 17:38:53
     */
    private String fullname;

    /**
     * @mbg.generated 2021-02-13 17:38:53
     */
    private String appellation;

    /**
     * @mbg.generated 2021-02-13 17:38:53
     */
    private String owner;

    /**
     * @mbg.generated 2021-02-13 17:38:53
     */
    private String company;

    /**
     * @mbg.generated 2021-02-13 17:38:53
     */
    private String job;

    /**
     * @mbg.generated 2021-02-13 17:38:53
     */
    private String email;

    /**
     * @mbg.generated 2021-02-13 17:38:53
     */
    private String phone;

    /**
     * @mbg.generated 2021-02-13 17:38:53
     */
    private String website;

    /**
     * @mbg.generated 2021-02-13 17:38:53
     */
    private String mphone;

    /**
     * @mbg.generated 2021-02-13 17:38:53
     */
    private String state;

    /**
     * @mbg.generated 2021-02-13 17:38:53
     */
    private String source;

    /**
     * @mbg.generated 2021-02-13 17:38:53
     */
    private String createBy;

    /**
     * @mbg.generated 2021-02-13 17:38:53
     */
    private String createTime;

    /**
     * @mbg.generated 2021-02-13 17:38:53
     */
    private String editBy;

    /**
     * @mbg.generated 2021-02-13 17:38:53
     */
    private String editTime;

    /**
     * @mbg.generated 2021-02-13 17:38:53
     */
    private String description;

    /**
     * @mbg.generated 2021-02-13 17:38:53
     */
    private String contactSummary;

    /**
     * @mbg.generated 2021-02-13 17:38:53
     */
    private String nextContactTime;

    /**
     * @mbg.generated 2021-02-13 17:38:53
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_clue
     *
     * @mbg.generated 2021-02-13 17:38:53
     */
    private static final long serialVersionUID = 1L;
}