package cn.syned.crm.workbench.entity;

import lombok.Data;

import java.io.Serializable;

/**
 * null
 *
 * @TableName tbl_contacts
 */
@Data
public class Contacts implements Serializable {
    /**
     * @mbg.generated 2021-02-18 20:56:39
     */
    private String id;

    /**
     * @mbg.generated 2021-02-18 20:56:39
     */
    private String owner;

    /**
     * @mbg.generated 2021-02-18 20:56:39
     */
    private String source;

    /**
     * @mbg.generated 2021-02-18 20:56:39
     */
    private String customerId;

    /**
     * @mbg.generated 2021-02-18 20:56:39
     */
    private String fullname;

    /**
     * @mbg.generated 2021-02-18 20:56:39
     */
    private String appellation;

    /**
     * @mbg.generated 2021-02-18 20:56:39
     */
    private String email;

    /**
     * @mbg.generated 2021-02-18 20:56:39
     */
    private String mphone;

    /**
     * @mbg.generated 2021-02-18 20:56:39
     */
    private String job;

    /**
     * @mbg.generated 2021-02-18 20:56:39
     */
    private String birth;

    /**
     * @mbg.generated 2021-02-18 20:56:39
     */
    private String createBy;

    /**
     * @mbg.generated 2021-02-18 20:56:39
     */
    private String createTime;

    /**
     * @mbg.generated 2021-02-18 20:56:39
     */
    private String editBy;

    /**
     * @mbg.generated 2021-02-18 20:56:39
     */
    private String editTime;

    /**
     * @mbg.generated 2021-02-18 20:56:39
     */
    private String description;

    /**
     * @mbg.generated 2021-02-18 20:56:39
     */
    private String contactSummary;

    /**
     * @mbg.generated 2021-02-18 20:56:39
     */
    private String nextContactTime;

    /**
     * @mbg.generated 2021-02-18 20:56:39
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_contacts
     *
     * @mbg.generated 2021-02-18 20:56:39
     */
    private static final long serialVersionUID = 1L;
}