package cn.syned.crm.workbench.entity;

import lombok.Data;

import java.io.Serializable;

/**
 * null
 *
 * @TableName tbl_customer
 */
@Data
public class Customer implements Serializable {
    /**
     * @mbg.generated 2021-02-18 20:57:19
     */
    private String id;

    /**
     * @mbg.generated 2021-02-18 20:57:19
     */
    private String owner;

    /**
     * @mbg.generated 2021-02-18 20:57:19
     */
    private String name;

    /**
     * @mbg.generated 2021-02-18 20:57:19
     */
    private String website;

    /**
     * @mbg.generated 2021-02-18 20:57:19
     */
    private String phone;

    /**
     * @mbg.generated 2021-02-18 20:57:19
     */
    private String createBy;

    /**
     * @mbg.generated 2021-02-18 20:57:19
     */
    private String createTime;

    /**
     * @mbg.generated 2021-02-18 20:57:19
     */
    private String editBy;

    /**
     * @mbg.generated 2021-02-18 20:57:19
     */
    private String editTime;

    /**
     * @mbg.generated 2021-02-18 20:57:19
     */
    private String contactSummary;

    /**
     * @mbg.generated 2021-02-18 20:57:19
     */
    private String nextContactTime;

    /**
     * @mbg.generated 2021-02-18 20:57:19
     */
    private String description;

    /**
     * @mbg.generated 2021-02-18 20:57:19
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_customer
     *
     * @mbg.generated 2021-02-18 20:57:19
     */
    private static final long serialVersionUID = 1L;
}