package cn.syned.crm.workbench.entity;

import lombok.Data;

import java.io.Serializable;

/**
 * null
 *
 * @TableName tbl_tran
 */
@Data
public class Tran implements Serializable {
    /**
     * @mbg.generated 2021-02-18 20:39:07
     */
    private String id;

    /**
     * @mbg.generated 2021-02-18 20:39:07
     */
    private String owner;

    /**
     * @mbg.generated 2021-02-18 20:39:07
     */
    private String money;

    /**
     * @mbg.generated 2021-02-18 20:39:07
     */
    private String name;

    /**
     * @mbg.generated 2021-02-18 20:39:07
     */
    private String expectedDate;

    /**
     * @mbg.generated 2021-02-18 20:39:07
     */
    private String customerId;

    /**
     * @mbg.generated 2021-02-18 20:39:07
     */
    private String stage;

    /**
     * @mbg.generated 2021-02-18 20:39:07
     */
    private String type;

    /**
     * @mbg.generated 2021-02-18 20:39:07
     */
    private String source;

    /**
     * @mbg.generated 2021-02-18 20:39:07
     */
    private String activityId;

    /**
     * @mbg.generated 2021-02-18 20:39:07
     */
    private String contactsId;

    /**
     * @mbg.generated 2021-02-18 20:39:07
     */
    private String createBy;

    /**
     * @mbg.generated 2021-02-18 20:39:07
     */
    private String createTime;

    /**
     * @mbg.generated 2021-02-18 20:39:07
     */
    private String editBy;

    /**
     * @mbg.generated 2021-02-18 20:39:07
     */
    private String editTime;

    /**
     * @mbg.generated 2021-02-18 20:39:07
     */
    private String description;

    /**
     * @mbg.generated 2021-02-18 20:39:07
     */
    private String contactSummary;

    /**
     * @mbg.generated 2021-02-18 20:39:07
     */
    private String nextContactTime;

    private String possibility;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tbl_tran
     *
     * @mbg.generated 2021-02-18 20:39:07
     */
    private static final long serialVersionUID = 1L;
}